"""Filesystem helpers — .gitignore management, run directories, YAML example generation."""

import shutil
from datetime import datetime
from pathlib import Path

from .config import get_binary_cfg, default_bin_cfg


# ── .gitignore ────────────────────────────────────────────────────────────────

def manage_gitignore(repo_root, track_checksum, log):
    gi    = Path(repo_root) / '.gitignore'
    text  = gi.read_text() if gi.exists() else ''
    lines = text.splitlines()
    changed = False

    def ensure(pat):
        nonlocal changed
        if pat not in lines:
            lines.append(pat)
            changed = True

    def remove(pat):
        nonlocal changed
        if pat in lines:
            lines.remove(pat)
            changed = True

    for pat in ('configs/*.bin', 'build/', 'logs/', '.bintxt_state',
                'bintxt_cfg.example.yaml'):
        ensure(pat)

    crc_pats = ['configs/*.crc32', 'configs/*.md5', 'configs/*.sha256']
    if track_checksum:
        for p in crc_pats:
            remove(p)
    else:
        for p in crc_pats:
            ensure(p)

    if changed:
        gi.write_text('\n'.join(lines) + '\n')
        log.info(".gitignore updated")


# ── Run directories ───────────────────────────────────────────────────────────

def setup_run_dirs(build_dir, log_dir, keep_runs):
    now       = datetime.now()
    date_part = now.strftime('%Y-%m-%d')
    time_part = now.strftime('%I-%M-%S') + now.strftime('%p').upper()
    counter   = 0
    prefix    = f'{date_part}_{time_part}'
    while (build_dir / f'{prefix}_{counter:03d}').exists():
        counter += 1
    ts      = f'{prefix}_{counter:03d}'
    run_dir = build_dir / ts
    (run_dir / 'packed').mkdir(parents=True, exist_ok=True)
    (build_dir / 'latest' / 'packed').mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)
    runs = sorted(build_dir.glob('????-??-??_*'), key=lambda p: p.stat().st_mtime)
    while len(runs) >= keep_runs:
        shutil.rmtree(runs.pop(0), ignore_errors=True)
    return run_dir, ts


# ── YAML example generator ────────────────────────────────────────────────────

def write_yaml_example(all_bases, cfg, defaults, script_dir, log):
    """Write bintxt_cfg.example.yaml — skeleton entries for every discovered binary."""
    ts  = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    out = script_dir / 'bintxt_cfg.example.yaml'

    UD = "  # UPDATE DEFAULT"

    def _fmt(val, key, override_cfg):
        return f"{val}{UD}" if override_cfg is None or key not in (override_cfg.get('format') or {}) else str(val)

    def _chk(val, override_cfg):
        chk_block = (override_cfg or {}).get('checksum') or {}
        return f"{val}{UD}" if 'algorithm' not in chk_block else val

    lines = [
        f"# Generated by bintxt.sh — {ts}",
        "# Effective configuration for all discovered binaries.",
        "# Fields marked '# UPDATE DEFAULT' are using global defaults —",
        "# verify they match your actual binary format before copying to bintxt_cfg.yaml.",
        "# Set label: true and populate labels: to enable @label injection during unpack.",
        "",
        "binaries:",
    ]

    raw_entries = {e.get('file'): e for e in (cfg.get('binaries') or [])}

    for base in sorted(all_bases):
        fname    = f'{base}.bin'
        raw      = raw_entries.get(fname)
        bc       = get_binary_cfg(cfg, fname, defaults) or default_bin_cfg(fname, defaults)
        no_entry = raw is None

        lines += [
            "",
            f"  - file: {fname}" + ("  # no entry in bintxt_cfg.yaml" if no_entry else ""),
            f"    label: {str(bc['label']).lower()}",
            f"    format:",
            f"      address_bits:   {_fmt(bc['address_bits'],   'address_bits',   raw)}",
            f"      word_bits:      {_fmt(bc['word_bits'],       'word_bits',       raw)}",
            f"      words_per_line: {_fmt(bc['words_per_line'],  'words_per_line',  raw)}",
            f"      endianness:     {_fmt(bc['endianness'],      'endianness',      raw)}",
            f"    checksum:",
            f"      algorithm: {_chk(bc['checksum_algorithm'], raw)}",
            f"    labels:",
        ]

        if bc['labels']:
            for lbl in bc['labels']:
                addr = int(lbl.get('address', 0))
                name = lbl.get('label', '')
                lines.append(f"      - address: 0x{addr:08x}")
                lines.append(f"        label: {name}")
        else:
            lines.append(f"      # Add one entry per label, e.g.:")
            lines.append(f"      # - address: 0x00000000")
            lines.append(f"      #   label: MY_LABEL")

    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    log.ok(f"YAML example written → {out.name}")
